# http://www.numpy.org
http://www.numpy.org/

Datasets can come from a wide range of sources and a wide range of formats,
including collections of documents, collections of images, collections of sound clips, collections 
of numerical measurements, or nearly anything else. Despite this apparent heterogeneity,
it will help us to think of all data fundamentally as arrays of numbers.

For example, images—particularly digital images—can be thought of as simply twodimensional 
arrays of numbers representing pixel brightness across the area. Sound
clips can be thought of as one-dimensional arrays of intensity versus time. Text can be
converted in various ways into numerical representations, perhaps binary digits rep‐
resenting the frequency of certain words or pairs of words. No matter what the data
are, the first step in making them analyzable will be to transform them into arrays of
numbers

 NumPy (short for Numerical Python) provides an efficient interface 
 to store and operate on dense data buffers. In some ways,
NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much
more efficient storage and data operations as the arrays grow larger in size

In [3]:
import numpy
numpy.__version__


'1.18.1'

In [5]:
numpy.__cached__

'C:\\Users\\gdg13\\anaconda\\lib\\site-packages\\numpy\\__pycache__\\__init__.cpython-37.pyc'

In [6]:
numpy?

In [12]:
numpy.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000001B620B8F288>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [13]:
from numpy import doc
#importing docstring doc from numpy package 

In [18]:
help(doc)
#to find help on doc docstring

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    c:\users\gdg13\anaconda\lib\site-packages\numpy\doc\__init__.py




help(numpy.doc.basics) 
# help(numpy.doc.TOPIC)
where topics are 
Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    =====================
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    c:\users\gdg13\anaconda\lib\site-packages\numpy\doc\__init__.py


In [21]:
#practice
result = 0
for i in range(100):
 result += i
result

4950

In [26]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
L?

In [28]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
L2


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [31]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
type(L[3])

int

In [12]:
L4=[str(c) for c in L3]
L4

['True', '2', '3.0', '4']

In [32]:
import array
L = list(range(10))
#A = array.array("f",L) # Here f denotes that so developed would contain float type 
A=array.array('f',L)
A


array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [33]:
array.array?

TypeError: array() argument 1 must be a unicode character, not list

In [28]:
import numpy as np
#np.array("f",L) as above array.array("f",L) do not work, rather np.array(L,"f") works.
np.array(L,dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.array(L,'str') # np.array can put str to obtain str array but array.array cannot

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [54]:
np.array(L) # even this works

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.array(L,"f") # There is just a positional difference array.array("f",L)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [60]:
np.array([1,2,3,4])
# as in list for python, arrays do not accept values with different datatype

 #If types do not match, NumPy will upcast if possible

array([1, 2, 3, 4])

In [66]:
np.array([1,"3",2.0])
#np.array([1,"3",2.0],"f") all are upcast to supreme dtype if no dtype is mentioned

array(['1', '3', '2.0'], dtype='<U11')

In [67]:
#if u want to explicitly set the data type use keyword dtype
np.array([1,2,3,4],dtype="f")

array([1., 2., 3., 4.], dtype=float32)

In [68]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [39]:
np.array(list(range(10)),'f')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [78]:
# creating an array containg 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
np.zeros(10,'f')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [79]:
# creating an array containing 15 ones of 3*5=15type
np.ones(3*5,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
# creating an array of 3X5 type 
np.ones((3,5),dtype=int) # or np.ones((3,4),'i')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.full((3,4),4.2) # if u have specified , which value needs to be filled , dtype description is not requred

array([[4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2]])

In [91]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14,dtype=int) # this dtype converts 3.14 into 3 otherwise if i remove dtype then 3.14 would be printed

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [94]:
# Create an array filled with a linear sequence
 # Starting at 0, ending at 20, stepping by 2
 # (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
np.arange(1,10,2) # np.arange also works same as linspace but only difference is np.arange only gives output as int.

array([1, 3, 5, 7, 9])

In [97]:
# create an array with equal spacing like 5 spaces between 1 and 2
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [61]:
np.linspace((2,3),1)

array([[2.        , 3.        ],
       [1.97959184, 2.95918367],
       [1.95918367, 2.91836735],
       [1.93877551, 2.87755102],
       [1.91836735, 2.83673469],
       [1.89795918, 2.79591837],
       [1.87755102, 2.75510204],
       [1.85714286, 2.71428571],
       [1.83673469, 2.67346939],
       [1.81632653, 2.63265306],
       [1.79591837, 2.59183673],
       [1.7755102 , 2.55102041],
       [1.75510204, 2.51020408],
       [1.73469388, 2.46938776],
       [1.71428571, 2.42857143],
       [1.69387755, 2.3877551 ],
       [1.67346939, 2.34693878],
       [1.65306122, 2.30612245],
       [1.63265306, 2.26530612],
       [1.6122449 , 2.2244898 ],
       [1.59183673, 2.18367347],
       [1.57142857, 2.14285714],
       [1.55102041, 2.10204082],
       [1.53061224, 2.06122449],
       [1.51020408, 2.02040816],
       [1.48979592, 1.97959184],
       [1.46938776, 1.93877551],
       [1.44897959, 1.89795918],
       [1.42857143, 1.85714286],
       [1.40816327, 1.81632653],
       [1.

In [64]:
np.linspace(1,2,6)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [110]:
#creating a 2x2 array with random floating numbers random.random takes atmost 1 arguement
np.random.random((2,2))

array([[0.82232682, 0.75068921],
       [0.98360176, 0.99603581]])

In [112]:
# Create a 3x3 array of normally distributed random values
 # with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))


array([[ 1.15863684,  1.07612783, -0.23490208],
       [-0.62111321, -1.38286196, -0.30802981],
       [ 0.44433098,  1.289029  , -1.41736193]])

In [113]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))


array([[6, 7, 0],
       [7, 2, 7],
       [9, 8, 6]])

In [117]:
#create a 3x3 identity matrix/ if dtype is not printed it is returning a float value
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [67]:
# Create an uninitialized array of three integers
 # The values will be whatever happens to already exist at that
 # memory location
np.empty(3)


array([0.02040816, 0.04081633, 0.08163265])

In [119]:
np.zeros(10, dtype='int16')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [93]:
import numpy as np
np.random.seed(0) # seed for1 reproducibility. when this is included , output for x1,x2 and x3 remains unaltered even after continuous runs 
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [7]:
print("x3 ndim: ", x3.ndim) # ndim helps return number of dimensions of an array
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
print("dtype:",x3.dtype)

dtype: int32


In [9]:
x3.size

60

In [10]:
# In general nbytes is supposed to be itemsize times size , i.e 4*60
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


# array indexing

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0] #searching an element through indexing

5

In [13]:
x1[-2] #used to call in reverse direction

7

In a multidimensional array, you access items using a comma-separated tuple of indices:

In [73]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[2,0] # first part i.e 2 represent row(3rd) and 0 represent column

1

In [16]:
x2[2,-1] # 3rd row and 1st element from reverse direction

7

In [74]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
# if u want to alter any of the values directly mention the value and assign to position
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [19]:
# in integer type array even if u assign a float value, that would automatically transform to int
x2[0,0]=3.14
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [79]:
#L2 = [str(c) for c in L]
#x5=[str(c) for c in (x2[1],x2[2],x2[0])]
x5=[str(c) for c in (x2)]
x5

['[3 5 2 4]', '[7 6 8 8]', '[1 6 7 7]']

In [21]:
x6=[str(c) for c in (x2[1])]
x6

['7', '6', '8', '8']

#  array slicing

: is called slice notation and is used for slicing.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x
>>> x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of
dimension, step=1

In [22]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[::2] # 0 is first element, 9 is last element , interval is 2

array([0, 2, 4, 6, 8])

In [24]:
x[:5] # values from address 5 and before

array([0, 1, 2, 3, 4])

In [25]:
x[1::2]

array([1, 3, 5, 7, 9])

In [26]:
# A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. 
x[::-2]
x[5::-2] # here last one is overwriting the prior one 

array([5, 3, 1])

# Multidimensional Array slicing

In [92]:
#Multidimensional slices work in the same way, with multiple slices separated by commas
x2

array([[3, 5, 2, 4],
       [5, 5, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[0:2,2:3] # The left part is rows part and the right one is columns portion 


array([[2],
       [8]])

In [29]:
x2[0:2,::2] # two rows and every second column (interval 2)

array([[3, 2],
       [7, 8]])

In [80]:
#Finally, subarray dimensions can even be reversed together:
x2[::-1,::-1]
# reversing is done by using -1 as interval in both rows and columns

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [81]:
x2[:,:1] #x2[:,0] prints the same

array([[3],
       [7],
       [1]])

One important—and extremely useful—thing to know about array slices is that they return views rather than copies of the 
array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. 
This means when we change values in sub arrays , actual parent array also changes

In [94]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [95]:
x2_change=x2[:2,:2]
x2_change

array([[3, 5],
       [7, 6]])

In [96]:
x2_change[0,0]=5
x2_change

array([[5, 5],
       [7, 6]])

In [97]:
x2 # this means a change in x2_change also led o change in parent array(x2)

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer.

# Creating copies of arrays

Despite the nice features of array views, it might be requirements sometimes to crreate a copy , hence copy() func. is taken into
use

In [98]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
# If we now make a change in x2_sub_copy , the original x2 array remains unaltered

[[5 5]
 [7 6]]


In [99]:
x2 # since we have used a copy function, the original array remains unaltered

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# Reshaping of Arrays

In [109]:
grid=np.arange(1,11)

In [110]:
grid

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
# now to reshape the array, we need to use .reshape() func.
s=grid.reshape(2,5)

In [112]:
s.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
np.arange(1,10).reshape(3,3) # THe above function can be used in two ways

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
#Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix
x = np.array([1, 2, 3])
x.reshape(1,3)

array([[1, 2, 3]])

In [117]:
x[np.newaxis, :] # Both gives same output

array([[1, 2, 3]])

In [118]:
x.reshape(3,1)
# x[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Concatenation of arrays

In [119]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [120]:
grid=np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [122]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [123]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [124]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [125]:
y=([[99],
    [99]])
np.hstack([grid,y]) #y is horizantally stacked to grid array

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Similarly, np.dstack will stack arrays along the third axis
Learn about this

In [77]:
import numpy as np
x = np.array((3, 5, 6))
y = np.array((8, 7, 9))
np.dstack((x,y))

array([[[3, 8],
        [5, 7],
        [6, 9]]])

In [75]:
x

array([3, 5, 6])

In [78]:
import numpy as np 
x= np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.dstack((x,y))

array([[[3, 5]],

       [[5, 7]],

       [[7, 9]]])